Backend Pt.1
andreacanog/Trendery pull request #1
Opened 2024-12-11 19:40 UTC by andreacanog

2024-12-16 14:56 UTC, ortizjs requested changes
Some minor comments. Let me know when you have had a chance to review them and let me know if you have any questions or need help :)

2024-12-16 14:56 UTC, ortizjs commented on app/models/user.rb
> +        user = User.find_by(email: credential)
I think here there is no need for `User.find_by` you can do: `user = find_by(email: credentials)`

2024-12-16 14:56 UTC, ortizjs commented on app/models/user.rb
> +       self.session_token
I think You can omit the self here:
```
update!(session_token: generate_unique_session_token)
session_token
```

2024-12-16 14:56 UTC, ortizjs commented on app/models/user.rb
> +          break token unless User.exists?(session_token: token)
No need for `User.exists?` you can just do `exists?(session_token: token)`

2024-12-16 14:56 UTC, ortizjs commented on app/models/user.rb
> +      self.session_token ||= self.class.generate_unique_session_token
Here you can just do: `self.session_token ||= generate_unique_session_token`
I can explain why later

2024-12-16 14:56 UTC, ortizjs commented on app/models/product.rb
> +      unless self.photo.attached?
No need for `self`. You can just do: `unless photo.attached?`

2024-12-16 14:56 UTC, ortizjs commented on app/models/product.rb
> +
Add a new empty lien after line 32

2025-02-10 19:23 UTC, ortizjs requested changes
Few minor comments

2025-02-10 19:23 UTC, ortizjs commented on app/models/order.rb
> +  validates :status, presence: true, inclusion: { in: %w[pending completed canceled] }
Can you check that it is actually `%w` and not `%i`

2025-02-10 19:23 UTC, ortizjs commented on app/models/cart_item.rb
> +
Remove extra line here

2025-02-10 19:23 UTC, ortizjs commented on app/models/order.rb
I think you can remove this extra line here

2025-02-10 19:37 UTC, andreacanog commented on app/models/order.rb
> +  validates :status, presence: true, inclusion: { in: %w[pending completed canceled] }
status is stored as a string in the database (as defined in db/schema.rb). Using %w creates an array of strings (e.g., ["pending", "completed", "canceled"]), which matches the type stored in the status column. If we use %i (symbols), the validation will fail because symbols (e.g., :pending) do not match the string values in the database.

2025-02-11 15:57 UTC, ortizjs approved these changes
LGTM

2025-02-20 17:48 UTC, merged