Feature/Backend pt.2
andreacanog/Trendery pull request #2
Opened 2024-12-18 23:26 UTC by andreacanog

2024-12-20 04:23 UTC, ortizjs requested changes
Minor comment

2024-12-20 04:23 UTC, ortizjs commented on app/controllers/api/v1/users_controller.rb
> +    before_action :require_logged_in, only: [:show, :update, :destroy]
I believe you can combine these: `before_action :set_user, :require_logged_in, only: [:show, :update, :destroy]
`

2025-02-21 21:21 UTC, ortizjs requested changes
Minor comments for the most part - let me know if you have any questions but we can also go through them together

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/application_controller.rb
> +      end
Lets review this method together to make sure I understand what is going on

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/application_controller.rb
> +
At new line at end of file

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/api/v1/products_controller.rb
> +
Add new line at end of file

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/api/v1/cart_items_controller.rb
> +
Add new line to end of file

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/application_controller.rb
> +    # CSRF protection for APIs
I would update this comment to just `# CSRF protection`

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/application_controller.rb
> +    # Handles unhandled exceptions and provides a JSON response for API clients
Remove the `for API clients` part of the code comment

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/api/v1/cart_items_controller.rb
> +      end
Same comment as before about wrapping in a `ActiveRecord::Base.transaction` transaction.

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/api/v1/sessions_controller.rb
> +
Add new line at end of file?

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/api/v1/sessions_controller.rb
> +      end
Can you check if it makes sense to wrap this logic in a `ActiveRecord::Base.transaction` transaction.

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/api/v1/carts_controller.rb
> +
I do not see a method for `create` - do you not need one?

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/api/v1/carts_controller.rb
> +
Add new line at end of file

2025-02-21 21:21 UTC, ortizjs commented on config/routes.rb
> +    resource :cart, only: [:show, :destroy]
I do not see a route for `create` - do you not need one?

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/api/v1/order_items_controller.rb
> +      @order_item = current_cart.order_items.build(order_item_params)
Lets discuss this as I am not sure what `.build` does. I would also look into potentially wrapping this in a transaction

2025-02-21 21:21 UTC, ortizjs commented on app/controllers/api/v1/order_items_controller.rb
> +
Add line at end of file

2025-02-24 19:11 UTC, andreacanog commented on app/controllers/api/v1/carts_controller.rb
> +
There's no create method in your CartsController because a cart is typically created automatically when a user logs in or performs an action that requires a cart.

2025-02-24 19:11 UTC, andreacanog commented on config/routes.rb
> +    resource :cart, only: [:show, :destroy]
There's no create method in your CartsController because a cart is typically created automatically when a user logs in or performs an action that requires a cart.

2025-02-24 22:43 UTC, andreacanog commented on app/controllers/api/v1/order_items_controller.rb
> +      @order_item = current_cart.order_items.build(order_item_params)
added a code comment to revisit this later

2025-02-24 23:46 UTC, andreacanog commented on app/controllers/api/v1/sessions_controller.rb
> +      end
It does not make sense because there are no database modifications that need to be rolled back in case of failure.

2025-02-25 18:03 UTC, ortizjs requested changes
Minor comment

2025-02-25 18:03 UTC, ortizjs commented on app/controllers/application_controller.rb
> +      return nil unless logged_in?  # Ensure user is logged in
Lets remove this

2025-02-25 18:42 UTC, ortizjs approved these changes
LGTM

2025-02-25 18:43 UTC, merged